train_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 2
  pin_memory: True
  num_workers: 2

val_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 2
  num_workers: 2
  shuffle: False
