defaults:
  - dataset: vctk_bwe_nuwave #voicebank_demand
  - dataloader: vctk_bwe_nuwave_dataloader #basic_dataloader
  - model: stft_unet #diffwave
  - _self_


experiment_name: ???
seed: 41113
checkpoint_dir: checkpoints

n_epochs: 1000
n_iters_per_epoch: 200
train_batch_size: 8 
val_batch_size: 8
accumulate_every: 4
save_model_every_epoch: 10
save_full_state_every: 10
log_every_iter: 1
compute_metric_every_epoch: 1 # not working now
visualize_every_epoch: 1
lr: 3e-4

# addons
spectral: false
adaptive_band: false


device: cuda

full_state_ckpt: null
model_ckpt: null